/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description health */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["HealthResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/readiness": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description ready */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ReadinessResponse"];
                    };
                };
                /** @description not ready */
                503: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ReadinessResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/ops-intelligence/meta": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description ops intelligence metadata */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["OpsIntelligenceMeta"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/symbols": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description symbol mappings */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["SymbolsResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/symbols/coverage": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description coverage matrix */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["CoverageResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/snapshot/liquidity": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: {
                    symbol?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description liquidity tab */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["LiquiditySnapshot"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/snapshot/quality": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: {
                    symbol?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description quality tab */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["QualitySnapshot"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/snapshot/share": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: {
                    window?: "24h" | "7d" | "30d";
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description market share tab */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ShareSnapshot"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/snapshot/top30": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: {
                    surface?: string;
                    platform?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description top30 tab */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Top30Snapshot"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/snapshot/top30/divergence": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description top30 CEX vs DEX divergence */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Top30DivergenceSnapshot"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/collection-status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description collector status */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["CollectionStatusResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/runtime-config": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description runtime config */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["RuntimeConfig"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/activity/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: {
                    platform?: string;
                    activity_type?: string;
                    status?: string;
                    review_status?: string;
                    limit?: number;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description activity events */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ActivityEventListResponse"];
                    };
                };
                /** @description activity disabled */
                503: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ActivityUnavailableResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/activity/events/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description activity event detail */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ActivityEventDetailResponse"];
                    };
                };
                /** @description activity disabled */
                503: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ActivityUnavailableResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/activity/source-health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: {
                    platform?: string;
                    source_status?: string;
                    enabled?: boolean;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description activity source health */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ActivitySourceHealthResponse"];
                    };
                };
                /** @description activity disabled */
                503: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ActivityUnavailableResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/activity/deliveries": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: {
                    limit?: number;
                    event_type?: string;
                    status?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description activity delivery outbox */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ActivityDeliveryListResponse"];
                    };
                };
                /** @description activity disabled */
                503: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ActivityUnavailableResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/activity/review/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: number;
                };
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["ActivityReviewRequest"];
                };
            };
            responses: {
                /** @description review updated */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ActivityMutationResponse"];
                    };
                };
                /** @description activity disabled */
                503: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ActivityUnavailableResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/activity/decision/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: number;
                };
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["ActivityDecisionRequest"];
                };
            };
            responses: {
                /** @description decision recorded */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ActivityMutationResponse"];
                    };
                };
                /** @description event version changed */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description activity disabled */
                503: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ActivityUnavailableResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/activity/deliveries/{id}/redrive": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: number;
                };
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["ActivityRedriveRequest"];
                };
            };
            responses: {
                /** @description redrive queued */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ActivityRedriveResponse"];
                    };
                };
                /** @description redrive not allowed */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description activity disabled */
                503: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ActivityUnavailableResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/listing/candidates": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: {
                    limit?: number;
                    status?: string;
                    evidence_kind?: string;
                    platform?: string;
                    symbol?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description listing candidates */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ListingCandidateListResponse"];
                    };
                };
                /** @description listing disabled */
                503: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ListingUnavailableResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/listing/candidates/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description candidate detail with signals */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ListingCandidateDetailResponse"];
                    };
                };
                /** @description listing disabled */
                503: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ListingUnavailableResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/listing/candidates/{id}/signals": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description candidate signals */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ListingSignalListResponse"];
                    };
                };
                /** @description listing disabled */
                503: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ListingUnavailableResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/listing/source-health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description listing source health */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ListingSourceHealthResponse"];
                    };
                };
                /** @description listing disabled */
                503: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ListingUnavailableResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/listing/deliveries": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: {
                    limit?: number;
                    event_type?: string;
                    status?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description listing delivery outbox */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ListingDeliveryListResponse"];
                    };
                };
                /** @description listing disabled */
                503: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ListingUnavailableResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @enum {string} */
        ApiStatus: "complete" | "partial" | "aggregated_orderbook" | "ws_limited_depth" | "stale" | "unsupported" | "error" | "insufficient_history";
        /** @enum {string} */
        DataFreshness: "live" | "delayed";
        NumberMap: {
            [key: string]: number;
        };
        StringMap: {
            [key: string]: string;
        };
        HealthResponse: {
            ok: boolean;
            service: string;
            product: string;
            display_name: string;
            mode: string;
            build_version: string;
            deps: {
                [key: string]: unknown;
            };
        };
        ReadinessResponse: {
            ready: boolean;
            build_version: string;
            checks: {
                [key: string]: unknown;
            };
        };
        SymbolMapping: {
            display_symbol: string;
            display_name?: string;
            canonical: string;
            asset_category?: string;
            market_surface: string;
            instrument_kind: string;
            lineage?: string;
            platform: string;
            api_symbol: string;
            base_asset: string;
            quote_asset: string;
            settle_asset: string;
            source_endpoint: string;
            contract_id?: string;
            market_id?: number;
            contract_size?: number;
            quanto_multiplier?: number;
            api_level_cap?: number;
            frontend_url?: string;
            url_verified?: boolean;
            catalog_status?: string;
        };
        SymbolsResponse: {
            symbols: string[];
            mappings: components["schemas"]["SymbolMapping"][];
        };
        CoverageRow: {
            platform: string;
            display_symbol: string;
            depth_status: components["schemas"]["ApiStatus"];
            source_endpoint: string;
        };
        CoverageResponse: {
            rows: components["schemas"]["CoverageRow"][];
            /** Format: date-time */
            snapshot_ts: string;
            latency_ms?: number;
        };
        DashboardCategorySymbol: {
            canonical: string;
            display_name: string;
            display_symbol: string;
            asset_category: string;
            instrument_kind: string;
            market_surface: string;
            lineage?: string;
            supported_platform_count: number;
        };
        DashboardCategory: {
            key: string;
            label: string;
            symbols: components["schemas"]["DashboardCategorySymbol"][];
        };
        CoinGeckoLineage: {
            enabled: boolean;
            exchange_ids?: string[];
            market_names?: string[];
            pull_interval?: string;
            /** Format: date-time */
            last_pull_ts?: string;
        };
        DataSources: {
            coingecko?: components["schemas"]["CoinGeckoLineage"];
        };
        OpsIntelligenceMeta: {
            tabs: string[];
            platforms: string[];
            symbols: string[];
            categories?: components["schemas"]["DashboardCategory"][];
            windows: string[];
            depth_tiers: number[];
            slippage_buckets_usd: number[];
            refresh_interval_sec: number;
            volume_discounts: components["schemas"]["NumberMap"];
            data_sources?: components["schemas"]["DataSources"];
        };
        DepthTierMetrics: {
            bid_usd: number;
            ask_usd: number;
            total_usd: number;
            depth_status?: components["schemas"]["ApiStatus"];
            partial_reason?: string;
            depth_source?: string;
            source_id?: string;
            source_endpoint?: string;
            levels_returned?: number;
            bid_levels_returned?: number;
            ask_levels_returned?: number;
            api_level_cap?: number;
            farthest_bid_pct?: number;
            farthest_ask_pct?: number;
            farthest_distance_pct?: number;
            aggregation_params?: components["schemas"]["StringMap"];
            strict_complete?: boolean;
            display_available?: boolean;
            policy_acceptance?: string;
            physical_limit?: boolean;
            unofficial_ui_endpoint?: boolean;
        };
        PlatformRow: {
            platform: string;
            platform_group?: string;
            display_platform?: string;
            is_edgex?: boolean;
            display_symbol: string;
            canonical_symbol?: string;
            venue_symbol?: string;
            market_surface?: string;
            instrument_kind?: string;
            lineage?: string;
            contract_id?: string;
            base_asset?: string;
            quote_asset?: string;
            /** Format: date-time */
            snapshot_ts: string;
            source_endpoint: string;
            depth_status: components["schemas"]["ApiStatus"];
            partial_reason?: string;
            error?: string;
            data_freshness?: components["schemas"]["DataFreshness"];
            last_collection_status?: components["schemas"]["ApiStatus"];
            last_collection_error?: string;
            /** Format: date-time */
            last_collection_ts?: string;
            mid_price?: number;
            spread_bp?: number;
            imbalance_pct?: number;
            depth_by_tier: {
                [key: string]: components["schemas"]["DepthTierMetrics"];
            };
            vs_median_by_tier?: components["schemas"]["NumberMap"];
            rank_0_1?: number;
            depth_status_label?: string;
            buy_slippage_bp: components["schemas"]["NumberMap"];
            sell_slippage_bp: components["schemas"]["NumberMap"];
            worst_slippage_bp?: components["schemas"]["NumberMap"];
            vs_median_spread_bp?: number | null;
            vs_median_slippage_bp?: components["schemas"]["NumberMap"];
            verdict?: string;
            funding?: components["schemas"]["PlatformFundingRate"];
        };
        PlatformFundingRate: {
            platform: string;
            platform_group?: string;
            display_platform?: string;
            is_edgex?: boolean;
            market_surface?: string;
            lineage?: string;
            display_symbol?: string;
            rate_8h?: number | null;
            rate_native?: number | null;
            period_hours?: number;
            status: components["schemas"]["ApiStatus"];
            source?: string;
            source_endpoint?: string;
            /** Format: date-time */
            snapshot_ts?: string;
            vs_median_8h?: number | null;
            rank_positive?: number | null;
            rank_negative?: number | null;
        };
        LiquidityKPIs: {
            edgex_depth_by_tier?: {
                [key: string]: components["schemas"]["DepthTierMetrics"];
            };
            edgex_vs_median_by_tier?: components["schemas"]["NumberMap"];
            strict_competitor_median_by_tier?: components["schemas"]["NumberMap"];
            competitor_median_by_tier?: components["schemas"]["NumberMap"];
            edgex_spread_bp?: number;
            edgex_spread_10m_bp?: number;
            edgex_spread_10m_status?: components["schemas"]["ApiStatus"];
            edgex_24h_share_pct?: number;
            edgex_24h_share_status?: components["schemas"]["ApiStatus"];
            symbol_share_7d_pct?: number;
            symbol_share_7d_status?: components["schemas"]["ApiStatus"];
            symbol_share_wow_status?: components["schemas"]["ApiStatus"];
            edgex_funding_rate_8h?: number | null;
            edgex_funding_rate_8h_status?: components["schemas"]["ApiStatus"];
            edgex_funding_rate_period_hours?: number;
            edgex_funding_rate_vs_median_8h?: number | null;
            competitor_funding_rate_median_8h?: number | null;
            competitor_funding_rate_median_8h_status?: components["schemas"]["ApiStatus"];
            competitor_funding_rate_median_8h_samples?: number;
        };
        QualityKPIs: {
            edgex_funding_rate_8h?: number | null;
            edgex_funding_rate_8h_status?: components["schemas"]["ApiStatus"];
            edgex_funding_rate_period_hours?: number;
            competitor_funding_rate_median_8h?: number | null;
            competitor_funding_rate_median_8h_status?: components["schemas"]["ApiStatus"];
            competitor_funding_rate_median_8h_samples?: number;
        };
        LiquiditySnapshot: {
            symbol: string;
            /** Format: date-time */
            snapshot_ts: string;
            rows: components["schemas"]["PlatformRow"][];
            competitor_median_by_tier?: components["schemas"]["NumberMap"];
            strict_competitor_median_by_tier?: components["schemas"]["NumberMap"];
            kpis?: components["schemas"]["LiquidityKPIs"];
        };
        QualitySnapshot: {
            symbol: string;
            /** Format: date-time */
            snapshot_ts: string;
            slippage_buckets_usd: number[];
            rows: components["schemas"]["PlatformRow"][];
            kpis?: components["schemas"]["QualityKPIs"];
        };
        ShareRow: {
            rank?: number;
            platform: string;
            platform_group?: string;
            display_platform?: string;
            is_edgex?: boolean;
            market_surface?: string;
            instrument_kind?: string;
            lineage?: string;
            aggregation_scope?: string;
            raw_volume_usd?: number;
            adjusted_volume_usd?: number;
            adjusted_volume_24h_usd?: number;
            adjusted_volume_total_usd?: number;
            share_pct?: number;
            denominator_pct?: number;
            discount?: number;
            status?: components["schemas"]["ApiStatus"];
            data_source?: string;
            days_seen?: number;
            days_window?: number;
        };
        ShareTrend: {
            status?: components["schemas"]["ApiStatus"];
            points?: {
                [key: string]: number | string;
            }[];
        };
        ShareHistory: {
            [key: string]: components["schemas"]["ApiStatus"];
        };
        ShareKPIs: {
            edgex_share_pct?: number;
            edgex_total_volume_usd?: number;
            denominator_usd?: number;
        };
        ShareSnapshot: {
            window: string;
            status?: components["schemas"]["ApiStatus"];
            reason?: string;
            /** Format: date-time */
            snapshot_ts: string;
            denominator_usd?: number;
            rows: components["schemas"]["ShareRow"][];
            kpis?: components["schemas"]["ShareKPIs"];
            history?: components["schemas"]["ShareHistory"];
            trend?: components["schemas"]["ShareTrend"];
        };
        ListedSurfaceDetail: {
            platform?: string;
            platform_group?: string;
            display_platform?: string;
            is_edgex?: boolean;
            display_symbol?: string;
            canonical_symbol?: string;
            venue_symbol?: string;
            market_surface?: string;
            instrument_kind?: string;
            lineage?: string;
            contract_id?: string;
            base_asset?: string;
            quote_asset?: string;
            source_endpoint?: string;
            status?: string;
        };
        Top30Row: {
            rank: number;
            platform: string;
            symbol: string;
            volume_24h_usd?: number;
            volume_7d_usd?: number;
            delta_7d_pct?: number;
            volume_7d_status?: components["schemas"]["ApiStatus"];
            delta_7d_status?: components["schemas"]["ApiStatus"];
            edgex_listed?: boolean;
            edgex_listed_surfaces?: components["schemas"]["ListedSurfaceDetail"][];
            edgex_listed_status?: components["schemas"]["ApiStatus"];
            competitor_top30_coverage?: number;
            competitor_top30_coverage_status?: components["schemas"]["ApiStatus"];
            suggested_action?: string;
            suggested_action_status?: components["schemas"]["ApiStatus"];
            status?: components["schemas"]["ApiStatus"];
            data_source?: string;
            source_endpoint?: string;
            /** Format: date-time */
            snapshot_ts?: string;
            error?: string;
        };
        Top30Snapshot: {
            surface: string;
            platform: string;
            /** Format: date-time */
            snapshot_ts: string;
            status?: components["schemas"]["ApiStatus"];
            rows: components["schemas"]["Top30Row"][];
        };
        Top30AggregateRow: {
            rank: number;
            symbol: string;
            adjusted_volume_24h_usd: number;
            raw_volume_24h_usd: number;
            platform_count: number;
            contributing_platforms?: string[];
        };
        Top30DivergenceRow: {
            symbol: string;
            cex_rank?: number | null;
            dex_rank?: number | null;
            cex_adjusted_volume_24h_usd?: number | null;
            dex_adjusted_volume_24h_usd?: number | null;
            cex_raw_volume_24h_usd?: number | null;
            dex_raw_volume_24h_usd?: number | null;
            cex_platform_count: number;
            dex_platform_count: number;
            rank_delta?: number | null;
            /** @enum {string} */
            category: "cex_only" | "dex_only" | "cex_heavy" | "dex_heavy" | "aligned";
            edgex_listed: boolean;
            edgex_listed_surfaces?: components["schemas"]["ListedSurfaceDetail"][];
            edgex_listed_status?: components["schemas"]["ApiStatus"];
        };
        Top30DivergenceKPI: {
            cex_only_count: number;
            dex_only_count: number;
            heavy_count: number;
            aligned_count: number;
            edgex_gap_count: number;
        };
        Top30DivergenceSnapshot: {
            /** Format: date-time */
            snapshot_ts: string;
            status: components["schemas"]["ApiStatus"];
            cex_platforms: string[];
            dex_platforms: string[];
            significant_rank_delta: number;
            cex_top30: components["schemas"]["Top30AggregateRow"][];
            dex_top30: components["schemas"]["Top30AggregateRow"][];
            divergence_rows: components["schemas"]["Top30DivergenceRow"][];
            kpi: components["schemas"]["Top30DivergenceKPI"];
        };
        RunSummary: {
            run_id?: string;
            /** Format: date-time */
            started_at?: string;
            /** Format: date-time */
            completed_at?: string;
            success?: number;
            failed?: number;
        };
        CollectionStatusRow: {
            platform?: string;
            platform_group?: string;
            display_platform?: string;
            is_edgex?: boolean;
            display_symbol?: string;
            canonical_symbol?: string;
            venue_symbol?: string;
            market_surface?: string;
            instrument_kind?: string;
            lineage?: string;
            contract_id?: string;
            base_asset?: string;
            quote_asset?: string;
            collector?: string;
            source_endpoint?: string;
            status?: components["schemas"]["ApiStatus"];
            error?: string;
            /** Format: date-time */
            snapshot_ts?: string;
        } & {
            [key: string]: unknown;
        };
        CollectionStatusResponse: {
            last_run: components["schemas"]["RunSummary"];
            rows: components["schemas"]["CollectionStatusRow"][];
        };
        RuntimeConfig: {
            [key: string]: unknown;
        };
        ActivityEventSummary: {
            id: number;
            platform: string;
            source_group: string;
            source_url?: string | null;
            title: string;
            activity_type: string;
            review_status: string;
            ops_decision_action?: string | null;
            event_status?: string;
            event_version: number;
            content_hash: string;
            dedupe_key: string;
            /** Format: date-time */
            publish_time?: string | null;
            needs_human_review?: boolean;
            auto_push_allowed?: boolean;
        } & {
            [key: string]: unknown;
        };
        ActivityEventSymbol: {
            event_id?: number;
            canonical_symbol?: string;
            display_symbol?: string;
            market_surface?: string;
            role?: string;
            sort_order?: number;
        } & {
            [key: string]: unknown;
        };
        ActivityRawEvidenceRef: {
            id?: number;
            source_key?: string;
            source_url?: string;
            /** Format: date-time */
            fetched_at?: string;
            payload_hash?: string;
        } & {
            [key: string]: unknown;
        };
        ActivityEventListResponse: {
            items: components["schemas"]["ActivityEventSummary"][];
            next_cursor?: string;
        };
        ActivityEventDetailResponse: {
            event: components["schemas"]["ActivityEventSummary"];
            symbols?: components["schemas"]["ActivityEventSymbol"][];
            raw_evidence_refs?: components["schemas"]["ActivityRawEvidenceRef"][];
        };
        ActivitySourceHealth: {
            id?: number;
            platform: string;
            source_group: string;
            source_type?: string;
            source_url?: string | null;
            source_key?: string;
            fetch_mode?: string;
            evidence_quality?: string;
            enabled: boolean;
            auto_push_enabled?: boolean;
            requires_proxy?: boolean;
            requires_browser_context?: boolean;
            requires_login?: boolean;
            personalized?: boolean;
            /** @description Compatibility alias for source_status. */
            status?: string;
            source_status?: string;
            poll_interval_seconds?: number;
            last_http_status?: number | null;
            last_error_kind?: string;
            last_schema_hash?: string | null;
            last_content_hash?: string | null;
            sample_count?: number;
            event_count?: number;
            source_context_json?: {
                [key: string]: unknown;
            };
            /** Format: date-time */
            disabled_until?: string | null;
            /** Format: date-time */
            last_checked_at?: string | null;
            /** Format: date-time */
            last_success_at?: string | null;
            /** Format: date-time */
            updated_at?: string;
        } & {
            [key: string]: unknown;
        };
        ActivitySourceHealthResponse: {
            items: components["schemas"]["ActivitySourceHealth"][];
        };
        ActivityDelivery: {
            id: number;
            event_type: string;
            dedupe_key: string;
            target_channel: string;
            status: string;
            attempt_count: number;
            max_attempts: number;
            last_error?: string;
            /** Format: date-time */
            created_at?: string;
            /** Format: date-time */
            updated_at?: string;
        } & {
            [key: string]: unknown;
        };
        ActivityDeliveryListResponse: {
            items: components["schemas"]["ActivityDelivery"][];
            next_cursor?: string;
        };
        ActivityReviewRequest: {
            /** @enum {string} */
            action: "approve" | "reject";
            reviewer?: string;
            reason?: string;
        };
        ActivityDecisionRequest: {
            /** @enum {string} */
            action: "follow_now" | "benchmark_watch" | "differentiate" | "no_follow" | "ignore_duplicate";
            version: number;
            token: string;
            reviewer?: string;
            reason?: string;
        };
        ActivityMutationResponse: {
            status?: string;
            event_id?: number;
            action?: string;
        } & {
            [key: string]: unknown;
        };
        ActivityRedriveRequest: {
            reason?: string;
            reviewer?: string;
        };
        ActivityRedriveResponse: {
            status?: string;
            id?: number;
        };
        ActivityUnavailableResponse: {
            status?: string;
            feature?: string;
            reason?: string;
        };
        ListingCandidate: {
            id?: number;
            canonical_symbol?: string;
            display_symbol?: string;
            market_surface?: string;
            instrument_kind?: string;
            lifecycle_status?: string;
            lifecycle_status_label?: string;
            evidence_kind?: string;
            confidence_level?: string;
            business_score?: number | null;
            business_score_version?: string;
            recommendation?: string;
            recommendation_label?: string;
            source_platforms?: string[];
            /** Format: date-time */
            first_observed_at?: string;
            /** Format: date-time */
            last_observed_at?: string;
        } & {
            [key: string]: unknown;
        };
        ListingCandidateListResponse: {
            candidates: components["schemas"]["ListingCandidate"][];
            count: number;
        };
        ListingCandidateDetailResponse: {
            candidate: components["schemas"]["ListingCandidate"];
            signals: components["schemas"]["ListingSignal"][];
        };
        ListingSignal: {
            id?: number;
            signal_type?: string;
            signal_subtype?: string;
            source_platform?: string;
            market_type?: string;
            api_symbol?: string;
            canonical_symbol?: string;
            display_symbol?: string;
            market_surface?: string;
            instrument_kind?: string;
            status_normalized?: string;
            confidence?: string;
            /** Format: date-time */
            observed_at?: string;
            /** Format: date-time */
            published_at?: string | null;
            /** Format: date-time */
            listing_time_ts?: string | null;
            fingerprint?: string;
            payload?: {
                [key: string]: unknown;
            };
            raw_payload?: {
                [key: string]: unknown;
            };
        } & {
            [key: string]: unknown;
        };
        ListingSignalListResponse: {
            signals: components["schemas"]["ListingSignal"][];
            count: number;
        };
        ListingSourceHealth: {
            source_key?: string;
            source_type?: string;
            platform?: string;
            status?: string;
            /** Format: date-time */
            last_success_at?: string | null;
            /** Format: date-time */
            last_error_at?: string | null;
            consecutive_error_count?: number;
            schema_drift_count?: number;
            /** Format: date-time */
            disabled_until?: string | null;
            last_error?: string;
            /** Format: date-time */
            updated_at?: string;
        };
        ListingSourceHealthResponse: {
            sources: components["schemas"]["ListingSourceHealth"][];
            count: number;
        };
        ListingDelivery: {
            id?: number;
            event_type?: string;
            dedupe_key?: string;
            target_channel?: string;
            status?: string;
            attempt_count?: number;
            max_attempts?: number;
            /** Format: date-time */
            next_attempt_at?: string | null;
            payload?: {
                [key: string]: unknown;
            };
            last_error?: string;
            /** Format: date-time */
            sent_at?: string | null;
            /** Format: date-time */
            created_at?: string;
            /** Format: date-time */
            updated_at?: string;
        } & {
            [key: string]: unknown;
        };
        ListingDeliveryListResponse: {
            deliveries: components["schemas"]["ListingDelivery"][];
            count: number;
        };
        ListingUnavailableResponse: {
            status: string;
            reason?: string;
            feature: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
