/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description health */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["HealthResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/readiness": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description ready */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ReadinessResponse"];
                    };
                };
                /** @description not ready */
                503: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ReadinessResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/dashboard/meta": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description dashboard metadata */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["DashboardMeta"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/symbols": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description symbol mappings */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["SymbolsResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/symbols/coverage": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description coverage matrix */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["CoverageResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/snapshot/liquidity": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: {
                    symbol?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description liquidity tab */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["LiquiditySnapshot"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/snapshot/quality": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: {
                    symbol?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description quality tab */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["QualitySnapshot"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/snapshot/share": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: {
                    window?: "24h" | "7d" | "30d";
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description market share tab */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ShareSnapshot"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/snapshot/top30": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: {
                    surface?: string;
                    platform?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description top30 tab */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Top30Snapshot"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/collection-status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description collector status */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["CollectionStatusResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/runtime-config": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description runtime config */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["RuntimeConfig"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @enum {string} */
        ApiStatus: "complete" | "partial" | "aggregated_orderbook" | "ws_limited_depth" | "stale" | "unsupported" | "error" | "insufficient_history";
        /** @enum {string} */
        DataFreshness: "live" | "delayed";
        NumberMap: {
            [key: string]: number;
        };
        StringMap: {
            [key: string]: string;
        };
        HealthResponse: {
            ok: boolean;
            service: string;
            mode: string;
            build_version: string;
            deps: {
                [key: string]: unknown;
            };
        };
        ReadinessResponse: {
            ready: boolean;
            build_version: string;
            checks: {
                [key: string]: unknown;
            };
        };
        SymbolMapping: {
            display_symbol: string;
            display_name?: string;
            canonical: string;
            asset_category?: string;
            market_surface: string;
            instrument_kind: string;
            lineage?: string;
            platform: string;
            api_symbol: string;
            base_asset: string;
            quote_asset: string;
            settle_asset: string;
            source_endpoint: string;
            contract_id?: string;
            market_id?: number;
            contract_size?: number;
            quanto_multiplier?: number;
            api_level_cap?: number;
            frontend_url?: string;
            url_verified?: boolean;
            catalog_status?: string;
        };
        SymbolsResponse: {
            symbols: string[];
            mappings: components["schemas"]["SymbolMapping"][];
        };
        CoverageRow: {
            platform: string;
            display_symbol: string;
            depth_status: components["schemas"]["ApiStatus"];
            source_endpoint: string;
        };
        CoverageResponse: {
            rows: components["schemas"]["CoverageRow"][];
            /** Format: date-time */
            snapshot_ts: string;
        };
        DashboardCategorySymbol: {
            canonical: string;
            display_name: string;
            display_symbol: string;
            asset_category: string;
            instrument_kind: string;
            market_surface: string;
            lineage?: string;
            supported_platform_count: number;
        };
        DashboardCategory: {
            key: string;
            label: string;
            symbols: components["schemas"]["DashboardCategorySymbol"][];
        };
        CoinGeckoLineage: {
            enabled: boolean;
            exchange_ids?: string[];
            market_names?: string[];
            pull_interval?: string;
            /** Format: date-time */
            last_pull_ts?: string;
        };
        DataSources: {
            coingecko?: components["schemas"]["CoinGeckoLineage"];
        };
        DashboardMeta: {
            tabs: string[];
            platforms: string[];
            symbols: string[];
            categories?: components["schemas"]["DashboardCategory"][];
            windows: string[];
            depth_tiers: number[];
            slippage_buckets_usd: number[];
            refresh_interval_sec: number;
            volume_discounts: components["schemas"]["NumberMap"];
            data_sources?: components["schemas"]["DataSources"];
        };
        DepthTierMetrics: {
            bid_usd: number;
            ask_usd: number;
            total_usd: number;
            depth_status?: components["schemas"]["ApiStatus"];
            partial_reason?: string;
            depth_source?: string;
            source_id?: string;
            source_endpoint?: string;
            levels_returned?: number;
            bid_levels_returned?: number;
            ask_levels_returned?: number;
            api_level_cap?: number;
            farthest_bid_pct?: number;
            farthest_ask_pct?: number;
            farthest_distance_pct?: number;
            aggregation_params?: components["schemas"]["StringMap"];
            strict_complete?: boolean;
            display_available?: boolean;
            policy_acceptance?: string;
            physical_limit?: boolean;
            unofficial_ui_endpoint?: boolean;
        };
        PlatformRow: {
            platform: string;
            display_symbol: string;
            /** Format: date-time */
            snapshot_ts: string;
            source_endpoint: string;
            depth_status: components["schemas"]["ApiStatus"];
            partial_reason?: string;
            error?: string;
            data_freshness?: components["schemas"]["DataFreshness"];
            last_collection_status?: components["schemas"]["ApiStatus"];
            last_collection_error?: string;
            /** Format: date-time */
            last_collection_ts?: string;
            mid_price?: number;
            spread_bp?: number;
            imbalance_pct?: number;
            depth_by_tier: {
                [key: string]: components["schemas"]["DepthTierMetrics"];
            };
            vs_median_by_tier?: components["schemas"]["NumberMap"];
            rank_0_1?: number;
            depth_status_label?: string;
            buy_slippage_bp: components["schemas"]["NumberMap"];
            sell_slippage_bp: components["schemas"]["NumberMap"];
            worst_slippage_bp?: components["schemas"]["NumberMap"];
            verdict?: string;
            funding?: components["schemas"]["PlatformFundingRate"];
        };
        PlatformFundingRate: {
            platform: string;
            display_symbol?: string;
            rate_8h?: number | null;
            rate_native?: number | null;
            period_hours?: number;
            status: components["schemas"]["ApiStatus"];
            source?: string;
            source_endpoint?: string;
            /** Format: date-time */
            snapshot_ts?: string;
            vs_median_8h?: number | null;
            rank?: number;
        };
        LiquidityKPIs: {
            edgex_depth_by_tier?: {
                [key: string]: components["schemas"]["DepthTierMetrics"];
            };
            edgex_vs_median_by_tier?: components["schemas"]["NumberMap"];
            strict_competitor_median_by_tier?: components["schemas"]["NumberMap"];
            competitor_median_by_tier?: components["schemas"]["NumberMap"];
            edgex_spread_bp?: number;
            edgex_spread_10m_bp?: number;
            edgex_spread_10m_status?: components["schemas"]["ApiStatus"];
            edgex_24h_share_pct?: number;
            symbol_share_7d_pct?: number;
            symbol_share_7d_status?: components["schemas"]["ApiStatus"];
            symbol_share_wow_status?: components["schemas"]["ApiStatus"];
            edgex_funding_rate_8h?: number | null;
            edgex_funding_rate_8h_status?: components["schemas"]["ApiStatus"];
            edgex_funding_rate_period_hours?: number;
            edgex_funding_rate_vs_median_8h?: number | null;
            competitor_funding_rate_median_8h?: number | null;
            competitor_funding_rate_median_8h_status?: components["schemas"]["ApiStatus"];
            competitor_funding_rate_median_8h_samples?: number;
        };
        QualityKPIs: {
            edgex_funding_rate_8h?: number | null;
            edgex_funding_rate_8h_status?: components["schemas"]["ApiStatus"];
            edgex_funding_rate_period_hours?: number;
            competitor_funding_rate_median_8h?: number | null;
            competitor_funding_rate_median_8h_status?: components["schemas"]["ApiStatus"];
            competitor_funding_rate_median_8h_samples?: number;
        };
        LiquiditySnapshot: {
            symbol: string;
            /** Format: date-time */
            snapshot_ts: string;
            rows: components["schemas"]["PlatformRow"][];
            competitor_median_by_tier?: components["schemas"]["NumberMap"];
            strict_competitor_median_by_tier?: components["schemas"]["NumberMap"];
            kpis?: components["schemas"]["LiquidityKPIs"];
        };
        QualitySnapshot: {
            symbol: string;
            /** Format: date-time */
            snapshot_ts: string;
            slippage_buckets_usd: number[];
            rows: components["schemas"]["PlatformRow"][];
            kpis?: components["schemas"]["QualityKPIs"];
        };
        ShareRow: {
            rank?: number;
            platform: string;
            raw_volume_usd?: number;
            adjusted_volume_usd?: number;
            adjusted_volume_24h_usd?: number;
            adjusted_volume_total_usd?: number;
            share_pct?: number;
            denominator_pct?: number;
            discount?: number;
            status?: components["schemas"]["ApiStatus"];
            data_source?: string;
            days_seen?: number;
            days_window?: number;
        };
        ShareTrend: {
            status?: components["schemas"]["ApiStatus"];
            points?: {
                [key: string]: number | string;
            }[];
        };
        ShareHistory: {
            [key: string]: components["schemas"]["ApiStatus"];
        };
        ShareKPIs: {
            edgex_share_pct?: number;
            edgex_total_volume_usd?: number;
            denominator_usd?: number;
        };
        ShareSnapshot: {
            window: string;
            status?: components["schemas"]["ApiStatus"];
            reason?: string;
            /** Format: date-time */
            snapshot_ts: string;
            denominator_usd?: number;
            rows: components["schemas"]["ShareRow"][];
            kpis?: components["schemas"]["ShareKPIs"];
            history?: components["schemas"]["ShareHistory"];
            trend?: components["schemas"]["ShareTrend"];
        };
        Top30Row: {
            rank: number;
            platform: string;
            symbol: string;
            volume_24h_usd?: number;
            volume_7d_usd?: number;
            delta_7d_pct?: number;
            volume_7d_status?: components["schemas"]["ApiStatus"];
            delta_7d_status?: components["schemas"]["ApiStatus"];
            edgex_listed?: boolean;
            edgex_listed_status?: components["schemas"]["ApiStatus"];
            competitor_top30_coverage?: number;
            competitor_top30_coverage_status?: components["schemas"]["ApiStatus"];
            suggested_action?: string;
            suggested_action_status?: components["schemas"]["ApiStatus"];
            status?: components["schemas"]["ApiStatus"];
            data_source?: string;
            source_endpoint?: string;
            /** Format: date-time */
            snapshot_ts?: string;
            error?: string;
        };
        Top30Snapshot: {
            surface: string;
            platform: string;
            /** Format: date-time */
            snapshot_ts: string;
            status?: components["schemas"]["ApiStatus"];
            rows: components["schemas"]["Top30Row"][];
        };
        RunSummary: {
            run_id?: string;
            /** Format: date-time */
            started_at?: string;
            /** Format: date-time */
            completed_at?: string;
            success?: number;
            failed?: number;
        };
        CollectionStatusRow: {
            platform?: string;
            display_symbol?: string;
            status?: components["schemas"]["ApiStatus"];
            error?: string;
            /** Format: date-time */
            snapshot_ts?: string;
        } & {
            [key: string]: unknown;
        };
        CollectionStatusResponse: {
            last_run: components["schemas"]["RunSummary"];
            rows: components["schemas"]["CollectionStatusRow"][];
        };
        RuntimeConfig: {
            [key: string]: unknown;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
