CREATE TABLE IF NOT EXISTS t_activity_source_state (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  platform VARCHAR(32) NOT NULL,
  source_group VARCHAR(96) NOT NULL,
  source_type VARCHAR(32) NOT NULL,
  source_url VARCHAR(512) NULL,
  source_key VARCHAR(191) NOT NULL UNIQUE,
  fetch_mode VARCHAR(32) NOT NULL,
  evidence_quality VARCHAR(32) NOT NULL DEFAULT 'unknown',
  enabled TINYINT(1) NOT NULL DEFAULT 1,
  poll_interval_seconds INT NOT NULL DEFAULT 3600,
  auto_push_enabled TINYINT(1) NOT NULL DEFAULT 1,
  requires_proxy TINYINT(1) NOT NULL DEFAULT 0,
  requires_browser_context TINYINT(1) NOT NULL DEFAULT 0,
  requires_login TINYINT(1) NOT NULL DEFAULT 0,
  region_sensitive TINYINT(1) NOT NULL DEFAULT 0,
  personalized TINYINT(1) NOT NULL DEFAULT 0,
  source_context_json JSON NULL,
  last_http_status INT NULL,
  last_error_kind VARCHAR(64) NULL,
  last_schema_hash CHAR(64) NULL,
  last_content_hash CHAR(64) NULL,
  sample_count INT NOT NULL DEFAULT 0,
  event_count INT NOT NULL DEFAULT 0,
  source_status VARCHAR(32) NOT NULL DEFAULT 'ok',
  disabled_until DATETIME(3) NULL,
  created_at DATETIME(3) NOT NULL,
  updated_at DATETIME(3) NOT NULL,
  KEY idx_activity_source_platform (platform),
  KEY idx_activity_source_group (source_group),
  KEY idx_activity_source_type (source_type),
  KEY idx_activity_source_fetch_mode (fetch_mode),
  KEY idx_activity_source_status (source_status, disabled_until)
);

CREATE TABLE IF NOT EXISTS t_activity_raw_evidence (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  source_key VARCHAR(191) NOT NULL,
  platform VARCHAR(32) NOT NULL,
  source_group VARCHAR(96) NOT NULL,
  source_url VARCHAR(512) NULL,
  fetch_mode VARCHAR(32) NOT NULL,
  payload_text LONGTEXT NULL,
  payload_hash CHAR(64) NOT NULL,
  schema_hash CHAR(64) NULL,
  content_hash CHAR(64) NULL,
  payload_size_bytes BIGINT UNSIGNED NOT NULL,
  payload_truncated TINYINT(1) NOT NULL DEFAULT 0,
  payload_preview MEDIUMTEXT NULL,
  response_meta_json JSON NULL,
  fixture_ref VARCHAR(255) NULL,
  fetched_at DATETIME(3) NOT NULL,
  created_at DATETIME(3) NOT NULL,
  updated_at DATETIME(3) NOT NULL,
  KEY idx_activity_raw_source_fetched (source_key, fetched_at),
  KEY idx_activity_raw_payload_hash (payload_hash)
);

CREATE TABLE IF NOT EXISTS t_activity_event (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  raw_evidence_id BIGINT UNSIGNED NULL,
  platform VARCHAR(32) NOT NULL,
  source_group VARCHAR(96) NOT NULL,
  source_external_id VARCHAR(191) NULL,
  source_url VARCHAR(512) NULL,
  title TEXT NOT NULL,
  activity_type VARCHAR(64) NOT NULL,
  target_symbols_json JSON NULL,
  reward_pool_text TEXT NULL,
  reward_pool_usd_estimate DECIMAL(28,8) NULL,
  reward_pool_primary_token VARCHAR(32) NULL,
  reward_pool_parse_confidence VARCHAR(32) NULL,
  has_reward_pool TINYINT(1) NOT NULL DEFAULT 0,
  start_time DATETIME(3) NULL,
  end_time DATETIME(3) NULL,
  publish_time DATETIME(3) NULL,
  raw_time_text TEXT NULL,
  raw_timezone_hint VARCHAR(64) NULL,
  time_parse_confidence VARCHAR(32) NULL,
  content_text MEDIUMTEXT NULL,
  content_hash CHAR(64) NOT NULL,
  dedupe_key VARCHAR(191) NOT NULL UNIQUE,
  confidence_score DECIMAL(8,4) NOT NULL DEFAULT 0,
  needs_human_review TINYINT(1) NOT NULL DEFAULT 0,
  auto_push_allowed TINYINT(1) NOT NULL DEFAULT 0,
  event_status VARCHAR(32) NOT NULL DEFAULT 'active',
  review_status VARCHAR(32) NOT NULL DEFAULT 'pending',
  ops_decision_action VARCHAR(32) NULL,
  ops_decision_stale TINYINT(1) NOT NULL DEFAULT 0,
  reviewer VARCHAR(128) NULL,
  review_reason TEXT NULL,
  reviewed_at DATETIME(3) NULL,
  event_version INT NOT NULL DEFAULT 1,
  parser_version VARCHAR(64) NOT NULL,
  source_context_json JSON NULL,
  parser_warnings_json JSON NULL,
  reward_pools_json JSON NULL,
  task_conditions_json JSON NULL,
  eligibility_rules_json JSON NULL,
  rich_fields_summary_json JSON NULL,
  created_at DATETIME(3) NOT NULL,
  updated_at DATETIME(3) NOT NULL,
  KEY idx_activity_event_platform_publish (platform, publish_time),
  KEY idx_activity_event_review_auto (review_status, auto_push_allowed),
  KEY idx_activity_event_status_updated (event_status, updated_at)
);
