package main

import "testing"

func TestDepthSourceDefaultsMatchAdapterPlan(t *testing.T) {
	if got := apiLevelCapDefault("binance"); got != 2000 {
		t.Fatalf("binance cap = %d, want 2000", got)
	}
	if got := apiLevelCapDefault("okx"); got != 10000 {
		t.Fatalf("okx cap = %d, want 10000", got)
	}
	if got := apiLevelCapDefault("bybit"); got != 2000 {
		t.Fatalf("bybit cap = %d, want 2000", got)
	}
	if got := sourceEndpointFor("okx"); got != "https://www.okx.com/api/v5/market/books-full" {
		t.Fatalf("okx source endpoint = %q", got)
	}
}

func TestCompareYAMLIgnoringTimestampIgnoresComments(t *testing.T) {
	existing := []byte(`# generated by humans
schema_version: 1
generated_at: 2026-05-20T00:00:00Z
platforms:
  okx:
    BTC:
      api_level_cap: 10000
`)
	generated := []byte(`schema_version: 1
generated_at: 2026-05-21T00:00:00Z
platforms:
  okx:
    BTC:
      api_level_cap: 10000
`)
	if diff, equal := compareYAMLIgnoringTimestamp(existing, generated); !equal {
		t.Fatalf("expected semantic equality ignoring comments/timestamp, diff:\n%s", diff)
	}
}

func TestShouldSkipCatalogDiffWhenDryRunHasFetchErrors(t *testing.T) {
	if shouldSkipCatalogDiff(nil) {
		t.Fatal("expected full dry-run to compare catalog")
	}
	if !shouldSkipCatalogDiff([]string{"binance: timeout"}) {
		t.Fatal("expected partial dry-run to skip semantic drift check")
	}
}
