-- Consolidated fresh-database schema for EdgeX Ops Intelligence.
--
-- Scope:
--   * Use this file only for fresh/empty database bootstrap review or manual
--     operator bootstrap. It is not a chronological migration chain.
--   * Existing/non-empty databases must be audited against backend/migrations/*.sql
--     and the guarded runtime post-init checks before production upgrades.
--
-- Runtime source of truth:
--   * Backend startup currently calls collector.ApplyMigrations(db), which executes
--     the compiled initSchemaSQL in backend/internal/collector/mysql_store.go and
--     then applySchemaPostInit. It does not scan or execute backend/migrations/*.sql.
--   * Keep this file in sync with initSchemaSQL, applySchemaPostInit, and the
--     latest migration number whenever schema changes.
--
-- Safety:
--   * This file intentionally does not CREATE DATABASE, USE a database, DROP
--     objects, or include any production data/secrets. Select the target database
--     explicitly in your mysql client before applying it.

SET NAMES utf8mb4;

CREATE TABLE IF NOT EXISTS t_symbol_mapping (id BIGINT AUTO_INCREMENT PRIMARY KEY, display_symbol VARCHAR(96) NOT NULL, canonical VARCHAR(32) NOT NULL, market_surface VARCHAR(32) NOT NULL, instrument_kind VARCHAR(32) NOT NULL, lineage VARCHAR(64) NOT NULL DEFAULT '', platform VARCHAR(32) NOT NULL, api_symbol VARCHAR(96) NOT NULL, contract_id VARCHAR(96) NOT NULL DEFAULT '', base_asset VARCHAR(64) NOT NULL DEFAULT '', quote_asset VARCHAR(64) NOT NULL DEFAULT '', source_endpoint VARCHAR(255) NOT NULL, UNIQUE KEY uk_symbol_mapping_identity (platform, display_symbol, market_surface, instrument_kind, lineage, api_symbol, contract_id));
CREATE TABLE IF NOT EXISTS t_orderbook_snapshot (id BIGINT AUTO_INCREMENT PRIMARY KEY, platform VARCHAR(32) NOT NULL, platform_group VARCHAR(32), display_platform VARCHAR(64), is_edgex TINYINT(1) NOT NULL DEFAULT 0, display_symbol VARCHAR(96) NOT NULL, canonical_symbol VARCHAR(64), venue_symbol VARCHAR(96), market_surface VARCHAR(32), instrument_kind VARCHAR(32), lineage VARCHAR(64), contract_id VARCHAR(96), base_asset VARCHAR(64), quote_asset VARCHAR(64), snapshot_ts TIMESTAMP NOT NULL, tier VARCHAR(16) NOT NULL DEFAULT '', bid_usd DECIMAL(28,8), ask_usd DECIMAL(28,8), total_usd DECIMAL(28,8), depth_status VARCHAR(32) NOT NULL, partial_reason VARCHAR(128), depth_source VARCHAR(32), source_id VARCHAR(64), levels_returned INT, bid_levels_returned INT, ask_levels_returned INT, api_level_cap INT, farthest_bid_pct DECIMAL(18,8), farthest_ask_pct DECIMAL(18,8), farthest_distance_pct DECIMAL(18,8), source_endpoint VARCHAR(255), aggregation_params_json JSON, strict_complete TINYINT(1) NOT NULL DEFAULT 0, display_available TINYINT(1) NOT NULL DEFAULT 0, policy_acceptance VARCHAR(32), physical_limit TINYINT(1) NOT NULL DEFAULT 0, unofficial_ui_endpoint TINYINT(1) NOT NULL DEFAULT 0, error_message TEXT, depth_json JSON, buy_slippage_json JSON, sell_slippage_json JSON);
CREATE TABLE IF NOT EXISTS t_book_quality_snapshot (id BIGINT AUTO_INCREMENT PRIMARY KEY, platform VARCHAR(32) NOT NULL, platform_group VARCHAR(32), display_platform VARCHAR(64), is_edgex TINYINT(1) NOT NULL DEFAULT 0, display_symbol VARCHAR(96) NOT NULL, canonical_symbol VARCHAR(64), venue_symbol VARCHAR(96), market_surface VARCHAR(32), instrument_kind VARCHAR(32), lineage VARCHAR(64), contract_id VARCHAR(96), base_asset VARCHAR(64), quote_asset VARCHAR(64), snapshot_ts TIMESTAMP NOT NULL, spread_bp DECIMAL(18,8), imbalance_pct DECIMAL(18,8));
CREATE TABLE IF NOT EXISTS t_symbol_volume_snapshot (id BIGINT AUTO_INCREMENT PRIMARY KEY, platform VARCHAR(32) NOT NULL, platform_group VARCHAR(32), display_platform VARCHAR(64), is_edgex TINYINT(1) NOT NULL DEFAULT 0, display_symbol VARCHAR(96) NOT NULL, canonical_symbol VARCHAR(64), venue_symbol VARCHAR(96), market_surface VARCHAR(32), instrument_kind VARCHAR(32), lineage VARCHAR(64), contract_id VARCHAR(96), base_asset VARCHAR(64), quote_asset VARCHAR(64), snapshot_ts TIMESTAMP NOT NULL, volume_24h_usd DECIMAL(28,8), status VARCHAR(32) NOT NULL, source_endpoint VARCHAR(255), error_message TEXT);
CREATE TABLE IF NOT EXISTS t_top30_snapshot (id BIGINT AUTO_INCREMENT PRIMARY KEY, platform VARCHAR(32) NOT NULL, symbol VARCHAR(96) NOT NULL, rank_no INT NOT NULL, volume_24h_usd DECIMAL(28,8), volume_7d_usd DECIMAL(28,8) NULL, delta_7d_pct DECIMAL(10,4) NULL, coverage_count INT NULL, edgex_listed TINYINT(1) NULL, suggested_action VARCHAR(64) NULL, data_source VARCHAR(32) NOT NULL DEFAULT 'coingecko', source_endpoint VARCHAR(255) NULL, status VARCHAR(32) NOT NULL, snapshot_ts TIMESTAMP NOT NULL, UNIQUE KEY uk_top30_platform_symbol_ts (platform, symbol, snapshot_ts));
CREATE TABLE IF NOT EXISTS t_daily_volume_aggregate (id BIGINT AUTO_INCREMENT PRIMARY KEY, platform VARCHAR(32) NOT NULL, display_symbol VARCHAR(96), day DATE NOT NULL, volume_usd DECIMAL(28,8), status VARCHAR(32) NOT NULL, data_source VARCHAR(32) NOT NULL DEFAULT 'native', source_endpoint VARCHAR(255) NULL, snapshot_ts TIMESTAMP NULL, UNIQUE KEY uk_day_platform_symbol_source (day, platform, display_symbol, data_source));
CREATE TABLE IF NOT EXISTS t_coingecko_platform_volume_snapshot (id BIGINT AUTO_INCREMENT PRIMARY KEY, platform VARCHAR(32) NOT NULL, snapshot_ts TIMESTAMP NOT NULL, volume_24h_usd DECIMAL(28,2), open_interest_usd DECIMAL(28,2), data_source VARCHAR(32) NOT NULL DEFAULT 'coingecko', source_endpoint VARCHAR(255) NOT NULL, status VARCHAR(32) NOT NULL, INDEX idx_cg_platform_ts (platform, snapshot_ts));
CREATE TABLE IF NOT EXISTS t_collection_run (id BIGINT AUTO_INCREMENT PRIMARY KEY, run_id VARCHAR(64) NOT NULL, started_at TIMESTAMP NOT NULL, completed_at TIMESTAMP, success_count INT, failed_count INT);
CREATE TABLE IF NOT EXISTS t_collection_status (id BIGINT AUTO_INCREMENT PRIMARY KEY, run_id VARCHAR(64) NOT NULL, platform VARCHAR(32) NOT NULL, platform_group VARCHAR(32), display_platform VARCHAR(64), is_edgex TINYINT(1) NOT NULL DEFAULT 0, display_symbol VARCHAR(96), canonical_symbol VARCHAR(64), venue_symbol VARCHAR(96), market_surface VARCHAR(32), instrument_kind VARCHAR(32), lineage VARCHAR(64), contract_id VARCHAR(96), base_asset VARCHAR(64), quote_asset VARCHAR(64), collector VARCHAR(32) NOT NULL, source_endpoint VARCHAR(255), status VARCHAR(32) NOT NULL, error_message TEXT, snapshot_ts TIMESTAMP NOT NULL, latency_ms BIGINT NOT NULL DEFAULT 0);
CREATE TABLE IF NOT EXISTS t_listing_instrument_snapshot (id BIGINT AUTO_INCREMENT PRIMARY KEY, platform VARCHAR(32) NOT NULL, market_type VARCHAR(32) NOT NULL, api_symbol VARCHAR(96) NOT NULL, api_market_id VARCHAR(96) NULL, display_symbol VARCHAR(128) NULL, canonical_symbol VARCHAR(64) NULL, base_asset VARCHAR(64) NULL, quote_asset VARCHAR(64) NULL, settle_asset VARCHAR(64) NULL, market_surface VARCHAR(32) NOT NULL, instrument_kind VARCHAR(32) NOT NULL, contract_type VARCHAR(64) NULL, status_raw VARCHAR(64) NULL, status_normalized VARCHAR(32) NOT NULL, status_field_name VARCHAR(64) NULL, listing_time_ts TIMESTAMP NULL, listing_time_field_name VARCHAR(64) NULL, delist_flag TINYINT(1) NOT NULL DEFAULT 0, first_seen_at TIMESTAMP NOT NULL, previous_seen_at TIMESTAMP NULL, last_seen_at TIMESTAMP NOT NULL, raw_json JSON NOT NULL, raw_json_hash VARCHAR(64) NOT NULL, normalizer_version VARCHAR(32) NOT NULL, created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP, UNIQUE KEY uk_listing_instrument (platform, market_type, api_symbol), KEY idx_listing_instrument_symbol (canonical_symbol, market_surface, instrument_kind), KEY idx_listing_instrument_status (platform, market_type, status_normalized, last_seen_at), KEY idx_listing_instrument_listing_time (listing_time_ts));
CREATE TABLE IF NOT EXISTS t_listing_announcement (id BIGINT AUTO_INCREMENT PRIMARY KEY, platform VARCHAR(32) NOT NULL, announcement_id VARCHAR(191) NOT NULL, announcement_url VARCHAR(512) NULL, title TEXT NOT NULL, description TEXT NULL, category VARCHAR(128) NULL, tags_json JSON NULL, language VARCHAR(32) NULL, published_at TIMESTAMP NULL, source_updated_at TIMESTAMP NULL, parsed_market_type VARCHAR(32) NULL, effective_listing_time TIMESTAMP NULL, parse_confidence VARCHAR(16) NOT NULL, raw_payload_json JSON NOT NULL, raw_payload_hash VARCHAR(64) NOT NULL, parser_version VARCHAR(32) NOT NULL, created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP, UNIQUE KEY uk_listing_announcement (platform, announcement_id), KEY idx_listing_announcement_published (platform, published_at), KEY idx_listing_announcement_hash (raw_payload_hash));
CREATE TABLE IF NOT EXISTS t_listing_announcement_symbol (id BIGINT AUTO_INCREMENT PRIMARY KEY, announcement_id BIGINT NOT NULL, canonical_symbol VARCHAR(64) NOT NULL, display_symbol VARCHAR(128) NULL, market_surface VARCHAR(32) NOT NULL, instrument_kind VARCHAR(32) NOT NULL, signal_subtype VARCHAR(64) NOT NULL, listing_time_ts TIMESTAMP NULL, created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, UNIQUE KEY uk_listing_announcement_symbol (announcement_id, canonical_symbol, market_surface, instrument_kind), KEY idx_listing_announcement_symbol_symbol (canonical_symbol, market_surface, instrument_kind));
CREATE TABLE IF NOT EXISTS t_listing_signal_observation (id BIGINT AUTO_INCREMENT PRIMARY KEY, signal_type VARCHAR(32) NOT NULL, signal_subtype VARCHAR(64) NULL, source_platform VARCHAR(32) NOT NULL, market_type VARCHAR(32) NULL, api_symbol VARCHAR(96) NULL, api_market_id VARCHAR(96) NULL, canonical_symbol VARCHAR(64) NOT NULL, display_symbol VARCHAR(128) NULL, base_asset VARCHAR(64) NULL, quote_asset VARCHAR(64) NULL, settle_asset VARCHAR(64) NULL, market_surface VARCHAR(32) NOT NULL, instrument_kind VARCHAR(32) NOT NULL, status_raw VARCHAR(64) NULL, status_normalized VARCHAR(32) NULL, confidence VARCHAR(16) NULL, observed_at TIMESTAMP NOT NULL, source_snapshot_ts TIMESTAMP NULL, published_at TIMESTAMP NULL, listing_time_ts TIMESTAMP NULL, source_endpoint VARCHAR(255) NULL, source_url VARCHAR(512) NULL, fingerprint VARCHAR(160) NOT NULL, payload_json JSON NOT NULL, raw_payload_json JSON NULL, raw_payload_hash VARCHAR(64) NULL, fused_at TIMESTAMP NULL, created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, UNIQUE KEY uk_listing_signal_fingerprint (fingerprint), KEY idx_listing_signal_type_time (signal_type, observed_at), KEY idx_listing_signal_identity (canonical_symbol, market_surface, instrument_kind, observed_at), KEY idx_listing_signal_unfused (fused_at, observed_at));
CREATE TABLE IF NOT EXISTS t_listing_candidate (id BIGINT AUTO_INCREMENT PRIMARY KEY, canonical_symbol VARCHAR(64) NOT NULL, display_symbol VARCHAR(128) NULL, market_surface VARCHAR(32) NOT NULL, instrument_kind VARCHAR(32) NOT NULL, lifecycle_status VARCHAR(64) NOT NULL, lifecycle_status_label VARCHAR(128) NULL, evidence_kind VARCHAR(64) NOT NULL, confidence_level VARCHAR(32) NOT NULL, business_score DECIMAL(10,4) NULL, business_score_version VARCHAR(32) NULL, recommendation VARCHAR(64) NULL, recommendation_label VARCHAR(128) NULL, source_platforms_json JSON NOT NULL, top30_enrichment_json JSON NULL, first_observed_at TIMESTAMP NOT NULL, last_observed_at TIMESTAMP NOT NULL, created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP, UNIQUE KEY uk_listing_candidate_identity (canonical_symbol, market_surface, instrument_kind), KEY idx_listing_candidate_status (lifecycle_status, last_observed_at), KEY idx_listing_candidate_score (business_score, last_observed_at));
CREATE TABLE IF NOT EXISTS t_listing_candidate_signal (id BIGINT AUTO_INCREMENT PRIMARY KEY, candidate_id BIGINT NOT NULL, signal_id BIGINT NOT NULL, created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, UNIQUE KEY uk_listing_candidate_signal (candidate_id, signal_id), KEY idx_listing_candidate_signal_signal (signal_id));
CREATE TABLE IF NOT EXISTS t_listing_source_state (id BIGINT AUTO_INCREMENT PRIMARY KEY, source_key VARCHAR(96) NOT NULL, source_type VARCHAR(32) NOT NULL, platform VARCHAR(32) NOT NULL, status VARCHAR(32) NOT NULL, last_success_at TIMESTAMP NULL, last_error_at TIMESTAMP NULL, consecutive_error_count INT NOT NULL DEFAULT 0, schema_drift_count INT NOT NULL DEFAULT 0, disabled_until TIMESTAMP NULL, last_error TEXT NULL, updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP, UNIQUE KEY uk_listing_source_state (source_key), KEY idx_listing_source_state_status (status, disabled_until));
CREATE TABLE IF NOT EXISTS t_listing_worker_lease (lease_name VARCHAR(96) NOT NULL, owner_id VARCHAR(96) NOT NULL, expires_at TIMESTAMP(6) NOT NULL, updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP, PRIMARY KEY (lease_name));
CREATE TABLE IF NOT EXISTS t_listing_risk_plan (id BIGINT AUTO_INCREMENT PRIMARY KEY, candidate_id BIGINT NOT NULL, risk_plan_version VARCHAR(32) NOT NULL, template_name VARCHAR(64) NOT NULL, max_leverage DECIMAL(18,8) NULL, max_position_usd DECIMAL(28,8) NULL, leverage_tiers_json JSON NOT NULL, funding_initial_mode VARCHAR(64) NULL, mm_quote_required TINYINT(1) NOT NULL DEFAULT 0, risk_notes_json JSON NULL, source_evidence_json JSON NOT NULL, generated_at TIMESTAMP NOT NULL, approved_at TIMESTAMP NULL, created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, KEY idx_listing_risk_plan_candidate (candidate_id, generated_at));
CREATE TABLE IF NOT EXISTS t_listing_decision (id BIGINT AUTO_INCREMENT PRIMARY KEY, candidate_id BIGINT NOT NULL, card_id VARCHAR(128) NULL, message_id VARCHAR(128) NULL, operator_open_id VARCHAR(128) NOT NULL, action VARCHAR(64) NOT NULL, reason TEXT NULL, signature_verified TINYINT(1) NOT NULL DEFAULT 0, callback_payload_json JSON NOT NULL, callback_ts TIMESTAMP NOT NULL, created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, UNIQUE KEY uk_listing_decision_idempotency (candidate_id, operator_open_id, action, callback_ts), KEY idx_listing_decision_candidate (candidate_id, created_at));
CREATE TABLE IF NOT EXISTS t_listing_watchlist (id BIGINT AUTO_INCREMENT PRIMARY KEY, candidate_id BIGINT NOT NULL, canonical_symbol VARCHAR(64) NOT NULL, market_surface VARCHAR(32) NOT NULL, instrument_kind VARCHAR(32) NOT NULL, watch_status VARCHAR(32) NOT NULL, watch_reason TEXT NULL, source_decision_id BIGINT NULL, watch_started_at TIMESTAMP NOT NULL, edgex_listed_at TIMESTAMP NULL, transferred_to_dashboard_at TIMESTAMP NULL, payload_json JSON NOT NULL, created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP, UNIQUE KEY uk_listing_watchlist_candidate (candidate_id), KEY idx_listing_watchlist_status (watch_status, watch_started_at));
CREATE TABLE IF NOT EXISTS t_listing_action_dispatch (id BIGINT AUTO_INCREMENT PRIMARY KEY, candidate_id BIGINT NOT NULL, decision_id BIGINT NOT NULL, dispatch_type VARCHAR(64) NOT NULL, target_channel VARCHAR(64) NOT NULL, status VARCHAR(32) NOT NULL, outbox_id BIGINT NULL, payload_json JSON NOT NULL, created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP, KEY idx_listing_action_dispatch_status (status, created_at), KEY idx_listing_action_dispatch_candidate (candidate_id, created_at));
CREATE TABLE IF NOT EXISTS t_listing_delivery_outbox (id BIGINT AUTO_INCREMENT PRIMARY KEY, event_type VARCHAR(64) NOT NULL, dedupe_key VARCHAR(191) NOT NULL, target_channel VARCHAR(64) NOT NULL, status VARCHAR(32) NOT NULL, attempt_count INT NOT NULL DEFAULT 0, max_attempts INT NOT NULL DEFAULT 5, next_attempt_at TIMESTAMP NULL, payload_json JSON NOT NULL, last_error TEXT NULL, sent_at TIMESTAMP NULL, created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP, UNIQUE KEY uk_listing_delivery_dedupe (dedupe_key), KEY idx_listing_delivery_due (status, next_attempt_at), KEY idx_listing_delivery_event (event_type, created_at));
CREATE TABLE IF NOT EXISTS t_listing_delivery_attempt (id BIGINT AUTO_INCREMENT PRIMARY KEY, outbox_id BIGINT NOT NULL, attempt_no INT NOT NULL, status VARCHAR(32) NOT NULL, http_status INT NULL, error_message TEXT NULL, attempted_at TIMESTAMP NOT NULL, response_body TEXT NULL, latency_ms BIGINT NOT NULL DEFAULT 0, created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, UNIQUE KEY uk_listing_delivery_attempt (outbox_id, attempt_no), KEY idx_listing_delivery_attempt_outbox (outbox_id, attempted_at));
CREATE TABLE IF NOT EXISTS t_listing_alert_state (id BIGINT AUTO_INCREMENT PRIMARY KEY, alert_kind VARCHAR(64) NOT NULL, canonical_symbol VARCHAR(64) NOT NULL, status VARCHAR(32) NOT NULL, severity_seq INT NOT NULL DEFAULT 1, reissue_count INT NOT NULL DEFAULT 0, clear_streak INT NOT NULL DEFAULT 0, first_triggered_at TIMESTAMP NOT NULL, last_pushed_at TIMESTAMP NULL, last_evaluated_at TIMESTAMP NOT NULL, last_severity_json JSON NULL, created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP, UNIQUE KEY uk_listing_alert_state (alert_kind, canonical_symbol), KEY idx_listing_alert_state_status (alert_kind, status, last_evaluated_at));
CREATE TABLE IF NOT EXISTS t_activity_source_state (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, platform VARCHAR(32) NOT NULL, source_group VARCHAR(96) NOT NULL, source_type VARCHAR(32) NOT NULL, source_url VARCHAR(512) NULL, source_key VARCHAR(191) NOT NULL UNIQUE, fetch_mode VARCHAR(32) NOT NULL, evidence_quality VARCHAR(32) NOT NULL DEFAULT 'unknown', enabled TINYINT(1) NOT NULL DEFAULT 1, poll_interval_seconds INT NOT NULL DEFAULT 3600, auto_push_enabled TINYINT(1) NOT NULL DEFAULT 1, requires_proxy TINYINT(1) NOT NULL DEFAULT 0, requires_browser_context TINYINT(1) NOT NULL DEFAULT 0, requires_login TINYINT(1) NOT NULL DEFAULT 0, region_sensitive TINYINT(1) NOT NULL DEFAULT 0, personalized TINYINT(1) NOT NULL DEFAULT 0, source_context_json JSON NULL, last_http_status INT NULL, last_error_kind VARCHAR(64) NULL, last_schema_hash CHAR(64) NULL, last_content_hash CHAR(64) NULL, sample_count INT NOT NULL DEFAULT 0, event_count INT NOT NULL DEFAULT 0, source_status VARCHAR(32) NOT NULL DEFAULT 'ok', disabled_until DATETIME(3) NULL, last_checked_at DATETIME(3) NULL, last_success_at DATETIME(3) NULL, producer_watermark_at DATETIME(3) NULL, bootstrap_completed_at DATETIME(3) NULL, created_at DATETIME(3) NOT NULL, updated_at DATETIME(3) NOT NULL, KEY idx_activity_source_platform (platform), KEY idx_activity_source_group (source_group), KEY idx_activity_source_type (source_type), KEY idx_activity_source_fetch_mode (fetch_mode), KEY idx_activity_source_status (source_status, disabled_until));
CREATE TABLE IF NOT EXISTS t_activity_raw_evidence (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, source_key VARCHAR(191) NOT NULL, platform VARCHAR(32) NOT NULL, source_group VARCHAR(96) NOT NULL, source_url VARCHAR(512) NULL, fetch_mode VARCHAR(32) NOT NULL, payload_text LONGTEXT NULL, payload_hash CHAR(64) NOT NULL, schema_hash CHAR(64) NULL, content_hash CHAR(64) NULL, payload_size_bytes BIGINT UNSIGNED NOT NULL, payload_truncated TINYINT(1) NOT NULL DEFAULT 0, payload_preview MEDIUMTEXT NULL, response_meta_json JSON NULL, fixture_ref VARCHAR(255) NULL, fetched_at DATETIME(3) NOT NULL, created_at DATETIME(3) NOT NULL, updated_at DATETIME(3) NOT NULL, KEY idx_activity_raw_source_fetched (source_key, fetched_at), KEY idx_activity_raw_payload_hash (payload_hash));
CREATE TABLE IF NOT EXISTS t_activity_event (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, raw_evidence_id BIGINT UNSIGNED NULL, platform VARCHAR(32) NOT NULL, source_group VARCHAR(96) NOT NULL, source_external_id VARCHAR(191) NULL, source_url VARCHAR(512) NULL, title TEXT NOT NULL, activity_type VARCHAR(64) NOT NULL, target_symbols_json JSON NULL, reward_pool_text TEXT NULL, reward_pool_usd_estimate DECIMAL(28,8) NULL, reward_pool_primary_token VARCHAR(32) NULL, reward_pool_parse_confidence VARCHAR(32) NULL, has_reward_pool TINYINT(1) NOT NULL DEFAULT 0, start_time DATETIME(3) NULL, end_time DATETIME(3) NULL, publish_time DATETIME(3) NULL, raw_time_text TEXT NULL, raw_timezone_hint VARCHAR(64) NULL, time_parse_confidence VARCHAR(32) NULL, content_text MEDIUMTEXT NULL, content_hash CHAR(64) NOT NULL, dedupe_key VARCHAR(191) NOT NULL UNIQUE, confidence_score DECIMAL(8,4) NOT NULL DEFAULT 0, needs_human_review TINYINT(1) NOT NULL DEFAULT 0, auto_push_allowed TINYINT(1) NOT NULL DEFAULT 0, event_status VARCHAR(32) NOT NULL DEFAULT 'active', review_status VARCHAR(32) NOT NULL DEFAULT 'pending', ops_decision_action VARCHAR(32) NULL, ops_decision_stale TINYINT(1) NOT NULL DEFAULT 0, reviewer VARCHAR(128) NULL, review_reason TEXT NULL, reviewed_at DATETIME(3) NULL, event_version INT NOT NULL DEFAULT 1, parser_version VARCHAR(64) NOT NULL, source_context_json JSON NULL, parser_warnings_json JSON NULL, reward_pools_json JSON NULL, task_conditions_json JSON NULL, eligibility_rules_json JSON NULL, rich_fields_summary_json JSON NULL, source_observed_at DATETIME(3) NULL, source_producer_watermark_at DATETIME(3) NULL, source_bootstrap_completed_at DATETIME(3) NULL, created_at DATETIME(3) NOT NULL, updated_at DATETIME(3) NOT NULL, KEY idx_activity_event_platform_publish (platform, publish_time), KEY idx_activity_event_review_auto (review_status, auto_push_allowed), KEY idx_activity_event_status_updated (event_status, updated_at));
CREATE TABLE IF NOT EXISTS t_activity_event_symbol (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, event_id BIGINT UNSIGNED NOT NULL, canonical_symbol VARCHAR(64) NOT NULL, display_symbol VARCHAR(128) NULL, market_surface VARCHAR(32) NOT NULL, role VARCHAR(32) NOT NULL, sort_order INT NOT NULL DEFAULT 0, created_at DATETIME(3) NOT NULL, updated_at DATETIME(3) NOT NULL, UNIQUE KEY uk_activity_event_symbol (event_id, canonical_symbol, market_surface, role), KEY idx_activity_event_symbol_lookup (canonical_symbol, market_surface));
CREATE TABLE IF NOT EXISTS t_activity_digest (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, digest_kind VARCHAR(32) NOT NULL, digest_key VARCHAR(64) NOT NULL, digest_date DATE NOT NULL, status VARCHAR(32) NOT NULL DEFAULT 'draft', summary_json JSON NULL, created_at DATETIME(3) NOT NULL, updated_at DATETIME(3) NOT NULL, UNIQUE KEY uk_activity_digest_key (digest_kind, digest_key));
CREATE TABLE IF NOT EXISTS t_activity_digest_item (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, digest_id BIGINT UNSIGNED NOT NULL, event_id BIGINT UNSIGNED NOT NULL, sort_order INT NOT NULL DEFAULT 0, severity VARCHAR(32) NULL, created_at DATETIME(3) NOT NULL, updated_at DATETIME(3) NOT NULL, UNIQUE KEY uk_activity_digest_item (digest_id, event_id), KEY idx_activity_digest_item_event (event_id));
CREATE TABLE IF NOT EXISTS t_activity_review_item (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, event_id BIGINT UNSIGNED NOT NULL, event_version INT NOT NULL, content_hash CHAR(64) NOT NULL, status VARCHAR(32) NOT NULL DEFAULT 'pending', reason TEXT NULL, reviewer VARCHAR(128) NULL, reviewed_at DATETIME(3) NULL, created_at DATETIME(3) NOT NULL, updated_at DATETIME(3) NOT NULL, KEY idx_activity_review_status (status, created_at), KEY idx_activity_review_event (event_id, event_version));
CREATE TABLE IF NOT EXISTS t_activity_delivery_outbox (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, event_type VARCHAR(64) NOT NULL, event_id BIGINT UNSIGNED NULL, event_version INT NULL, dedupe_key VARCHAR(191) NOT NULL UNIQUE, target_channel VARCHAR(64) NOT NULL, status VARCHAR(32) NOT NULL, attempt_count INT NOT NULL DEFAULT 0, max_attempts INT NOT NULL DEFAULT 5, next_attempt_at DATETIME(3) NULL, payload_json JSON NOT NULL, last_error TEXT NULL, sent_at DATETIME(3) NULL, created_at DATETIME(3) NOT NULL, updated_at DATETIME(3) NOT NULL, CHECK (status IN ('pending','retry','sent','failed','disabled_no_webhook','disabled_missing_secret','muted','redrive_pending')), KEY idx_activity_delivery_due (status, next_attempt_at), KEY idx_activity_delivery_event (event_type, created_at));
CREATE TABLE IF NOT EXISTS t_activity_delivery_attempt (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, outbox_id BIGINT UNSIGNED NOT NULL, attempt_no INT NOT NULL, status VARCHAR(32) NOT NULL, http_status INT NULL, error_message TEXT NULL, attempted_at DATETIME(3) NOT NULL, response_body TEXT NULL, latency_ms BIGINT NOT NULL DEFAULT 0, created_at DATETIME(3) NOT NULL, updated_at DATETIME(3) NOT NULL, UNIQUE KEY uk_activity_delivery_attempt (outbox_id, attempt_no), KEY idx_activity_delivery_attempt_outbox (outbox_id, attempted_at));
CREATE TABLE IF NOT EXISTS t_activity_worker_lease (lease_name VARCHAR(191) NOT NULL PRIMARY KEY, owner VARCHAR(191) NOT NULL, expires_at DATETIME(3) NOT NULL, heartbeat_at DATETIME(3) NULL, created_at DATETIME(3) NOT NULL, updated_at DATETIME(3) NOT NULL);
